import {useCallback,useEffect,useState} from 'react';
import {BookOpen,FileUp,Search,ShieldCheck,Trash2} from 'lucide-react';
import {DataTable,Drawer,EmptyState,Facts,JsonDetails,Loading,Notice,Status,Tabs,Toolbar,date,fmt,items,object,request,text,useRemote,type RecordValue} from './WorkspaceUI';

type Region={kind:string;text:string;headers:string;rows:string;definitions:string};
const region=(block:RecordValue):Region=>({kind:text(block.kind,'paragraph')==='table'?'table':text(block.kind)==='equation'?'equation':'paragraph',
  text:text(block.text,''),headers:(object(block.details).headers as string[]||[]).join(' | '),
  rows:((object(block.details).rows as string[][])||[]).map(r=>r.join(' | ')).join('\n'),definitions:text(object(block.details).symbol_definitions,'')});
export default function KnowledgeWorkspace({onAsk}:{onAsk:(reference:RecordValue)=>void}){
  const info=useRemote<RecordValue>('/v2/workspace');const owner=object(info.data?.user).role==='owner';
  const inventory=useRemote<{items:RecordValue[]}>(info.data?'/v2/knowledge/'+(owner?'inventory':'documents'):null);
  const [query,setQuery]=useState(''),[asOf,setAsOf]=useState(''),[rerank,setRerank]=useState(false),[results,setResults]=useState<RecordValue|null>(null);
  const [selected,setSelected]=useState<RecordValue|null>(null),[tab,setTab]=useState('content'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  const [uploadTarget,setUploadTarget]=useState<RecordValue|null>(null),[versionLabel,setVersionLabel]=useState('v1');
  const [uploadOpen,setUploadOpen]=useState(false),[file,setFile]=useState<File|null>(null),[title,setTitle]=useState(''),[author,setAuthor]=useState(''),[source,setSource]=useState(''),[authorization,setAuthorization]=useState(''),[license,setLicense]=useState('未核实外部许可，仅本地研究'),[classification,setClassification]=useState('internal');
  const [review,setReview]=useState(''),[pages,setPages]=useState(''),[blockIndex,setBlockIndex]=useState(0),[regions,setRegions]=useState<Region[]>([]),[readers,setReaders]=useState(''),[readRoles,setReadRoles]=useState<string[]>([]),[confirmDelete,setConfirmDelete]=useState(false),[hours,setHours]=useState(24),[tokens,setTokens]=useState(1200),[consentReason,setConsentReason]=useState('');
  const selectedId=selected?text(selected.doc_id):'',version=selected?Number(selected.version):1;
  const base=selected?'/v2/knowledge/documents/'+selectedId+'/versions/'+version:null;
  const detail=useRemote<RecordValue>(base),history=useRemote<{items:RecordValue[]}>(base?base+'/parses':null),consents=useRemote<{items:RecordValue[]}>(owner&&base?base+'/disclosures':null);
  const parsed=object(detail.data?.parsed),blocks=items(parsed.blocks),metadata=object(detail.data?.metadata??selected?.metadata);
  const closeUpload=useCallback(()=>setUploadOpen(false),[]);
  const close=useCallback(()=>{setSelected(null);setRegions([]);setConfirmDelete(false);setError('');setMessage('');},[]);
  useEffect(()=>{if(!detail.data){setRegions([]);setReview('');return;}setBlockIndex(0);setRegions(blocks[0]?[region(blocks[0])]:[]);setReview('');},[detail.data]);
  useEffect(()=>{if(selected){const access=object(selected.access);setReaders((access.readers as string[]||[]).join(', '));setReadRoles(access.read_roles as string[]||[]);setTab('content');}},[selected]);
  async function perform(action:()=>Promise<unknown>,success:string){setBusy(true);setError('');setMessage('');try{await action();setResults(null);setMessage(success);inventory.reload();detail.reload();history.reload();consents.reload();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function search(){setBusy(true);setError('');try{setResults(await request('/v2/knowledge/search',{body:{query,rerank,as_of:asOf?new Date(asOf).toISOString():null,limit:5}}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function upload(){if(!file)return;await perform(async()=>{const format=file.name.split('.').at(-1)?.toLowerCase();if(!['md','docx','pdf'].includes(format||''))throw new Error('请选择 MD、DOCX 或 PDF 文件');const registered=await request<RecordValue>('/v2/knowledge/documents',{body:{doc_id:uploadTarget?.doc_id||crypto.randomUUID().replaceAll('-',''),title:title||file.name,author,source:source||file.name,authorization,license,classification,version_label:versionLabel,format,effective_at:new Date().toISOString(),readers:object(uploadTarget?.access).readers||[],read_roles:object(uploadTarget?.access).read_roles||[]}});
    await request('/v2/knowledge/documents/'+registered.doc_id+'/versions/'+registered.version+'/content',{method:'PUT',body:file});
    setUploadOpen(false);setSelected(registered);setFile(null);
  },'文档已接入，请检查解析结果。');}
  function chooseBlock(index:number){setBlockIndex(index);setRegions([region(blocks[index])]);}
  async function saveCorrections(){if(!base||!detail.data)return;await perform(()=>request(base+'/corrections',{body:{expected_parse_hash:detail.data?.parse_hash,note:review,corrections:[{block_id:blocks[blockIndex]?.block_id,regions:regions.map(r=>({kind:r.kind,text:r.text,headers:r.kind==='table'?r.headers.split('|').map(v=>v.trim()):[],rows:r.kind==='table'?r.rows.split('\n').filter(v=>v.trim()).map(row=>row.split('|').map(v=>v.trim())):[],definitions:r.definitions}))}]}}),'修订已保存，需审核后重建索引。');}
  async function grant(){if(!base||!detail.data)return;await perform(()=>request(base+'/disclosures',{body:{document_hash:detail.data?.content_hash,parse_hash:detail.data?.index_parse_hash,provider:'deepseek-flash',max_excerpt_tokens:tokens,expires_at:new Date(Date.now()+hours*3600000).toISOString(),reason:consentReason}}),'正文授权已登记。');}
  const searchRows=items(results?.items);
  return <section className="workspace-stack">
    <Toolbar title="文档知识" onRefresh={inventory.reload}>{owner?<button className="primary" onClick={()=>{setUploadTarget(null);setVersionLabel('v1');setFile(null);setUploadOpen(true);setError('');setMessage('');}}><FileUp size={16}/>接入文档</button>:null}</Toolbar>
    <section className="workspace-panel"><form className="knowledge-search" onSubmit={e=>{e.preventDefault();void search();}}><label className="sr-only" htmlFor="knowledge-query">检索问题</label><input id="knowledge-query" placeholder="查找时间合同、规程、模型说明…" value={query} onChange={e=>setQuery(e.target.value)} required/><button className="primary" disabled={busy||!query.trim()}><Search size={17}/>检索</button></form><div className="knowledge-options"><label>依据时刻<input aria-label="知识依据时刻" type="datetime-local" value={asOf} onChange={e=>setAsOf(e.target.value)}/></label><label><input type="checkbox" checked={rerank} onChange={e=>setRerank(e.target.checked)}/>使用本地深度重排（较慢）</label></div></section>
    {error?<Notice tone="error">{error}</Notice>:null}{message?<Notice tone="success">{message}</Notice>:null}
    {results?<section className="workspace-stack"><Toolbar title={'检索结果 · '+searchRows.length+' 条'}/>{searchRows.length?searchRows.map((row,i)=>{const c=object(row.citation);return <article className="knowledge-hit" key={text(c.chunk_id)}><div><span className="workspace-overline">{text(c.doc_id)} · 版本 {text(c.version)}</span><strong>{text(c.heading,'文档片段')}</strong><small>{c.page?'第 '+text(c.page)+' 页':'行 '+text(object(c.location).line_start)} · {text(row.kind)}</small></div><p>{text(row.text)}</p><div className="workspace-actions"><button onClick={()=>setSelected({doc_id:c.doc_id,version:c.version})}><BookOpen size={15}/>查看来源</button><button onClick={()=>onAsk({chunk_id:c.chunk_id,hash:c.hash,parse_hash:c.parse_hash,as_of:c.as_of})}>带入研究对话</button><a href={text(c.source_url)} target="_blank" rel="noreferrer">打开原文</a></div></article>;}):<EmptyState title="没有可访问的匹配结果">检查关键词、依据时刻，或确认文档已完成审核与索引。</EmptyState>}</section>:null}
    <section className="workspace-stack"><Toolbar title={owner?'文档与版本':'当前可访问文档'}/>{inventory.error?<Notice tone="error">{inventory.error}</Notice>:null}{inventory.loading&&!inventory.data?<Loading/>:inventory.data?.items.length?<DataTable rows={inventory.data.items} onRow={setSelected} columns={[{key:'title',label:'文档',render:r=><div><strong>{text(object(r.metadata).title)}</strong><small className="workspace-id">{text(r.doc_id)}</small></div>},{key:'version',label:'版本',render:r=>text(object(r.metadata).version_label,r.version?.toString())},{key:'status',label:'状态',render:r=><Status value={r.revoked?'revoked':r.status??'indexed'}/>},{key:'classification',label:'密级',render:r=>(({public:'公开',internal:'内部',confidential:'保密'} as Record<string,string>)[text(object(r.metadata).classification)]||text(object(r.metadata).classification))},{key:'effective_at',label:'生效时间',render:r=>date(text(object(r.metadata).effective_at))}]}/>:<EmptyState title="知识库还没有可用文档">接入文件后，按解析、审核、索引的顺序生成可追溯引用。</EmptyState>}</section>
    {uploadOpen?<Drawer title={uploadTarget?"新增文档版本":"接入文档"} onClose={closeUpload}><form className="workspace-stack" onSubmit={e=>{e.preventDefault();void upload();}}><label className="field">本地文件<input type="file" accept=".md,.docx,.pdf" required onChange={e=>{const value=e.target.files?.[0]||null;setFile(value);if(value){setTitle(value.name);setSource(value.name);}}}/></label><label className="field">名称<input value={title} onChange={e=>setTitle(e.target.value)} required/></label><label className="field">版本标识<input value={versionLabel} onChange={e=>setVersionLabel(e.target.value)} required/></label><label className="field">作者或维护者<input value={author} onChange={e=>setAuthor(e.target.value)} placeholder="未标注时请填写“未标注”" required/></label><label className="field">来源<input value={source} onChange={e=>setSource(e.target.value)} required/></label><label className="field">接入依据<textarea value={authorization} onChange={e=>setAuthorization(e.target.value)} required placeholder="说明文件来源与本地使用授权"/></label><label className="field">许可说明<input value={license} onChange={e=>setLicense(e.target.value)} required/></label><label className="field">密级<select value={classification} onChange={e=>setClassification(e.target.value)}><option value="internal">内部</option><option value="confidential">保密</option><option value="public">公开</option></select></label><Notice>文件先进入本地知识库，默认仅项目管理员可访问。正文供模型读取需要另行授权。</Notice><button className="primary" disabled={busy||!file}>{busy?'正在解析…':'登记并解析'}</button>{error?<Notice tone="error">{error}</Notice>:null}</form></Drawer>:null}
    {selected?<Drawer title={text(metadata.title,'文档详情')} onClose={close}>{detail.loading&&!detail.data?<Loading/>:null}{detail.error?<Notice tone="error">{detail.error}</Notice>:null}<Status value={detail.data?.status}/>{owner&&detail.data?<button className="secondary" onClick={()=>{const existing=inventory.data?.items.find(v=>v.doc_id===selectedId);setUploadTarget({doc_id:selectedId,access:existing?.access});setTitle(text(metadata.title,""));setAuthor(text(metadata.author,""));setSource(text(metadata.source,""));setAuthorization(text(metadata.authorization,""));setLicense(text(metadata.license,""));setClassification(text(metadata.classification,"internal"));setVersionLabel("v"+(version+1));setFile(null);close();setUploadOpen(true);}}>新增版本</button>:null}<Facts values={[{label:'文档版本',value:text(metadata.version_label)},{label:'来源',value:text(metadata.source)},{label:'生效 / 失效',value:date(text(metadata.effective_at))+' / '+date(metadata.expires_at?text(metadata.expires_at):undefined)},{label:'正文哈希',value:<code>{text(detail.data?.content_hash)}</code>}]}/>
      <Tabs value={tab} onChange={setTab} options={[{id:'content',label:'内容与审核'},{id:'corrections',label:'结构校正'},{id:'access',label:'权限与授权'},{id:'versions',label:'解析历史'}]}/>
      {tab==='content'?<section className="workspace-stack">{base&&detail.data?.content_hash?<a className="workspace-link" href={'/api'+base+'/source'} target="_blank" rel="noreferrer">打开原文副本</a>:null}
        {metadata.format==='pdf'&&base?<img className="knowledge-page" src={'/api'+base+'/pages/1.png'} alt="PDF 第 1 页，供原文核对"/>:null}
        {items(parsed.issues).length?<Notice>{items(parsed.issues).map(v=>text(v.reason)).join('、')}</Notice>:null}
        <div className="knowledge-blocks">{blocks.map(block=><article key={text(block.block_id)}><div><Status value={block.kind}/><small>{object(block.location).page?'第 '+text(object(block.location).page)+' 页':'行 '+text(object(block.location).line_start)}</small></div><pre>{text(block.text,'没有识别文字')}</pre>{object(object(block.details).ocr).minimum_score!==undefined?<small>识别分数 {fmt(object(object(block.details).ocr).minimum_score,3)}（非校准正确率）</small>:null}</article>)}</div>
        {owner&&detail.data?<><label className="field">核对说明<textarea value={review} onChange={e=>setReview(e.target.value)} placeholder="记录表格、单位、公式和版面的核对结果"/></label><div className="workspace-actions"><button disabled={busy||!review.trim()} onClick={()=>void perform(()=>request(base+'/review',{body:{accepted:true,note:review,expected_parse_hash:detail.data?.parse_hash}}),'审核通过。')}>核对通过</button><button disabled={busy||!review.trim()} onClick={()=>void perform(()=>request(base+'/review',{body:{accepted:false,note:review,expected_parse_hash:detail.data?.parse_hash}}),'已退回。')}>退回修订</button><button className="primary" disabled={busy||!['parsed','indexed'].includes(text(detail.data.status))} onClick={()=>void perform(()=>request(base+'/index',{body:{}}),'索引已更新。')}>建立索引</button></div>
          {metadata.format==='pdf'?<div className="workspace-actions"><label className="field">OCR 页码（留空处理待识别页）<input value={pages} onChange={e=>setPages(e.target.value)} placeholder="1,2,3"/></label><button disabled={busy} onClick={()=>void perform(()=>request(base+'/ocr',{body:{expected_parse_hash:detail.data?.parse_hash,pages:pages.trim()?pages.split(',').map(Number):null}}),'OCR 已完成，请核对结果。')}>执行本地 OCR</button></div>:null}
          <button disabled={busy} onClick={()=>void perform(()=>request(base+'/reparse',{body:{expected_parse_hash:detail.data?.parse_hash}}),'重新解析完成，旧索引保留至审核重建。')}>从原文重新解析</button></>:null}
      </section>:tab==='corrections'?<section className="workspace-stack">{owner?<><label className="field">修订结构块<select value={blockIndex} onChange={e=>chooseBlock(Number(e.target.value))}>{blocks.map((v,i)=><option key={text(v.block_id)} value={i}>{text(v.kind)} · {text(v.heading,'块 '+i)}</option>)}</select></label>{regions.map((r,i)=><section className="workspace-region" key={i}><label className="field">区域类型<select value={r.kind} onChange={e=>setRegions(old=>old.map((v,j)=>j===i?{...v,kind:e.target.value}:v))}><option value="paragraph">正文</option><option value="heading">标题</option><option value="table">表格</option><option value="equation">公式</option><option value="image">图片说明</option></select></label>
        {r.kind==='table'?<><label className="field">表头（用 | 分列，保留单位）<input value={r.headers} onChange={e=>setRegions(old=>old.map((v,j)=>j===i?{...v,headers:e.target.value}:v))}/></label><label className="field">完整数据行（每行一条，用 | 分列）<textarea rows={6} value={r.rows} onChange={e=>setRegions(old=>old.map((v,j)=>j===i?{...v,rows:e.target.value}:v))}/></label></>:<label className="field">核对后的内容<textarea rows={5} value={r.text} onChange={e=>setRegions(old=>old.map((v,j)=>j===i?{...v,text:e.target.value}:v))}/></label>}
        {r.kind==='equation'?<label className="field">符号定义<textarea value={r.definitions} onChange={e=>setRegions(old=>old.map((v,j)=>j===i?{...v,definitions:e.target.value}:v))}/></label>:null}{regions.length>1?<button onClick={()=>setRegions(old=>old.filter((_,j)=>j!==i))}>移除此区域</button>:null}</section>)}
        <button onClick={()=>setRegions(old=>[...old,{kind:'paragraph',text:'',headers:'',rows:'',definitions:''}])}>增加区域</button><label className="field">修订说明<textarea value={review} onChange={e=>setReview(e.target.value)}/></label><button className="primary" disabled={busy||!review.trim()||!regions.length} onClick={()=>void saveCorrections()}>保存修订</button></>:<Notice>当前账号可读取文档，结构修订由管理员处理。</Notice>}</section>:tab==='access'?<section className="workspace-stack">{owner?<><h3>读取权限</h3><label className="field">允许的账号（逗号分隔）<input value={readers} onChange={e=>setReaders(e.target.value)}/></label><div className="workspace-actions">{['researcher','viewer'].map(role=><label key={role}><input type="checkbox" checked={readRoles.includes(role)} onChange={e=>setReadRoles(old=>e.target.checked?[...old,role]:old.filter(v=>v!==role))}/>{role==='researcher'?'研究员':'只读用户'}</label>)}</div><button disabled={busy} onClick={()=>void perform(()=>request('/v2/knowledge/documents/'+selectedId+'/access',{method:'PUT',body:{readers:readers.split(',').map(v=>v.trim()).filter(Boolean),read_roles:readRoles,revoked:false}}),'读取权限已更新。')}>保存读取权限</button>
          <h3>允许模型读取正文</h3><Notice>授权目标为 DeepSeek Flash，绑定当前正文与解析哈希。请先核对本版本内容和使用范围。</Notice><div className="workspace-form-grid"><label className="field">有效小时<input type="number" min={1} max={720} value={hours} onChange={e=>setHours(Number(e.target.value))}/></label><label className="field">片段长度估算上限<input type="number" min={64} max={2000} value={tokens} onChange={e=>setTokens(Number(e.target.value))}/></label></div><label className="field">用途说明<textarea value={consentReason} onChange={e=>setConsentReason(e.target.value)}/></label><button className="primary" disabled={busy||detail.data?.status!=='indexed'||!consentReason.trim()} onClick={()=>void grant()}><ShieldCheck size={16}/>授权本版本正文</button>
          {consents.data?.items.map(v=><div className="knowledge-consent" key={text(v.id)}><div><strong>{text(v.provider)}</strong><small>到期 {date(text(v.expires_at))} · {v.revoked?'已撤销':'已登记'}</small></div><button disabled={busy||!!v.revoked} onClick={()=>void perform(()=>request('/v2/knowledge/documents/'+selectedId+'/disclosures/'+text(v.id)+'/revoke',{body:{}}),'正文授权已撤销。')}>撤销授权</button></div>)}
          <details className="workspace-danger"><summary>撤销或删除知识库副本</summary><p>撤销立即停止访问；删除会清理知识库原文、索引和关联派生回答。</p><button disabled={busy} onClick={()=>void perform(()=>request('/v2/knowledge/documents/'+selectedId+'/access',{method:'PUT',body:{readers:[],read_roles:[],revoked:true}}),'文档已撤销。')}>撤销文档访问</button><button onClick={()=>setConfirmDelete(true)}><Trash2 size={15}/>删除知识库副本</button>{confirmDelete?<Notice tone="error">确认删除“{text(metadata.title)}”？<button disabled={busy} onClick={()=>void perform(async()=>{await request('/v2/knowledge/documents/'+selectedId,{method:'DELETE'});close();},'知识库副本已删除。')}>确认删除</button></Notice>:null}</details>
        </>:<Notice>读取权限与正文授权由项目管理员管理。</Notice>}</section>:<section className="workspace-stack">{history.data?.items.length?<DataTable rows={history.data.items} columns={[{key:'revision',label:'修订'},{key:'operation',label:'操作'},{key:'actor_id',label:'记录者'},{key:'at',label:'时间',render:r=>date(text(r.at))},{key:'parse_hash',label:'哈希',render:r=><code>{text(r.parse_hash).slice(0,16)}</code>}]}/>:<EmptyState title="暂无解析历史"/>}<JsonDetails value={detail.data}/></section>}
      {busy?<Loading/>:null}{error?<Notice tone="error">{error}</Notice>:null}{message?<Notice tone="success">{message}</Notice>:null}
    </Drawer>:null}
  </section>;
}
