import {useCallback,useEffect,useMemo,useState,type ReactNode} from 'react';
import {Play,Plus,ShieldCheck} from 'lucide-react';
import {DataTable,Drawer,EmptyState,Facts,JsonDetails,Loading,Notice,Status,Tabs,Toolbar,date,fmt,items,object,request,text,useRemote,type RecordValue} from './WorkspaceUI';
const outputLabel=(value:unknown)=>({reference:'当前观测参考',joint:'联合双目标',two_independent_estimators:'双目标独立模型',joint_two_target_head:'联合双目标',two_independent_posterior_models:'双目标后验模型',two_independent_expression_searches:'双目标符号表达式',two_independent_context_models:'双目标预训练模型'} as Record<string,string>)[text(value)]||text(value);
const uncertaintyLabel=(value:unknown)=>{const name=text(value,'');if(!name||name==='unsupported')return '未开放区间';if(name.includes('std'))return '原生标准差（未校准）';if(name.includes('quantile'))return '原生分位数（未校准）';return name;};
type Selection={kind:'method'|'comparison'|'artifact'|'calibration'|'ensemble';row:RecordValue};
const metricsColumns=[{key:'method_id',label:'方法'},{key:'target',label:'目标 / 单位',render:(r:RecordValue)=>(r.target==='cu'?'Cu':'As')+' · '+text(r.unit,r.target==='cu'?'g/L':'mg/L')},{key:'n',label:'样本',render:(r:RecordValue)=>fmt(r.n??r.common_events,0)},{key:'mae',label:'MAE',render:(r:RecordValue)=>fmt(r.mae,4)},{key:'rmse',label:'RMSE',render:(r:RecordValue)=>fmt(r.rmse,4)},{key:'picp',label:'区间覆盖',render:(r:RecordValue)=>r.picp===undefined?'—':fmt(Number(r.picp)*100,1)+'%'}];
export default function ModelsWorkspace({legacy,eventId}:{legacy:ReactNode;eventId:string}){
  const [tab,setTab]=useState('registry'),[search,setSearch]=useState(''),[selection,setSelection]=useState<Selection|null>(null);
  const [methodSet,setMethodSet]=useState<string[]>(['Persistence','DeltaRidge']),[seed,setSeed]=useState(20260911);
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[operation,setOperation]=useState<RecordValue|null>(null);
  const [sourceKind,setSourceKind]=useState('model_comparison'),[sourceId,setSourceId]=useState(''),[artifactMethod,setArtifactMethod]=useState('Persistence'),[target,setTarget]=useState('cu');
  const catalog=useRemote<{items:RecordValue[]}>('/v2/models'),comparisons=useRemote<{items:RecordValue[]}>('/v2/model-comparisons');
  const artifacts=useRemote<{items:RecordValue[]}>('/v2/model-artifacts'),calibrations=useRemote<{items:RecordValue[]}>('/v2/calibrations');
  const ensembles=useRemote<{items:RecordValue[]}>('/v2/ensemble-studies'),pointers=useRemote<RecordValue>('/v2/model-pointers'),info=useRemote<RecordValue>('/v2/workspace');
  const [shadowId,setShadowId]=useState(''),[gate,setGate]=useState<RecordValue|null>(null);
  const close=useCallback(()=>{setSelection(null);setOperation(null);setShadowId('');setGate(null);setError('');},[]);
  const canCompute=!!info.data&&object(info.data.user).role!=='viewer',canApprove=object(info.data?.user).role==='owner';
  const paths={comparison:'/v2/model-comparisons/',artifact:'/v2/model-artifacts/',calibration:'/v2/calibrations/',ensemble:'/v2/ensemble-studies/'};
  const selectedId=selection?text(selection.row.id??selection.row.run_id):'';
  const detail=useRemote<RecordValue>(selection&&selection.kind!=='method'?paths[selection.kind]+selectedId:null);
  const current=selection?.kind==='method'?selection.row:detail.data;
  const descriptor=object(current?.descriptor),result=object(current?.result);
  useEffect(()=>{if(!current||!['queued','running'].includes(text(current.status)))return;const timer=setInterval(()=>{detail.reload();comparisons.reload();calibrations.reload();},1600);return()=>clearInterval(timer);},[current?.status,detail.reload,comparisons.reload,calibrations.reload]);
  const methods=(catalog.data?.items||[]).filter(row=>(text(row.method_id)+' '+text(row.implementation)).toLowerCase().includes(search.toLowerCase()));
  const sources=sourceKind==='calibration_study'?calibrations.data?.items:sourceKind==='ensemble_study'?ensembles.data?.items:comparisons.data?.items;
  const completed=(sources||[]).filter(row=>row.status==='completed');
  const selectedSource=useRemote<RecordValue>(sourceId?(sourceKind==='calibration_study'?'/v2/calibrations/':sourceKind==='ensemble_study'?'/v2/ensemble-studies/':'/v2/model-comparisons/')+sourceId:null);
  const sourceMethods=useMemo(()=>{const value=selectedSource.data;if(!value)return [];const req=object(value.request);const list=Array.isArray(req.methods)?req.methods:Array.isArray(object(value.result).methods)?object(value.result).methods:[];return (list as unknown[]).map(v=>typeof v==='string'?v:text(object(v).method_id)).filter(Boolean);},[selectedSource.data]);
  async function execute(action:()=>Promise<RecordValue>){setBusy(true);setError('');try{const value=await action();setOperation(value);artifacts.reload();comparisons.reload();calibrations.reload();pointers.reload();detail.reload();return value;}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function startComparison(calibration=false){await execute(async()=>{const payload={request_key:crypto.randomUUID(),methods:methodSet,seeds:[seed]};const value=await request<RecordValue>(calibration?'/v2/calibrations':'/v2/model-comparisons',{body:calibration?payload:{request_key:payload.request_key,methods:methodSet,seed}});setSelection({kind:calibration?'calibration':'comparison',row:value});return value;});}
  async function registerArtifact(){await execute(()=>request('/v2/model-artifacts',{body:{request_key:crypto.randomUUID(),source_kind:sourceKind,source_id:sourceId,method_id:artifactMethod,target}}));}
  async function shadow(){const value=await execute(()=>request('/v2/model-artifacts/'+selectedId+'/shadow',{body:{request_key:crypto.randomUUID(),samples_per_fold:8}}));if(value){setShadowId(text(value.id));try{setGate(await request<RecordValue>('/v2/model-artifacts/'+selectedId+'/qualification?shadow_id='+text(value.id)));}catch(e){setError((e as Error).message);}}}
  async function propose(){await execute(async()=>{const latest=await request<RecordValue>('/v2/model-pointers');const active=object(latest[text(descriptor.target)]);return request('/v2/releases',{body:{request_key:crypto.randomUUID(),candidate_id:selectedId,shadow_id:shadowId,target:descriptor.target,expected_version:active.version??0,reason:'依据当前工件和影子验证创建研究发布提案'}});});}
  const currentCollection=tab==='comparisons'?comparisons:tab==='calibration'?calibrations:tab==='ensembles'?ensembles:artifacts;
  const rows=tab==='comparisons'?(comparisons.data?.items||[]):tab==='calibration'?(calibrations.data?.items||[]):tab==='ensembles'?(ensembles.data?.items||[]):(artifacts.data?.items||[]);
  return <section className="workspace-stack">
    <div className="workspace-champions">{['cu','as'].map(t=>{const pointer=object(pointers.data?.[t]);const artifact=artifacts.data?.items.find(a=>a.id===pointer.candidate_id);return <div key={t}><span>{t==='cu'?'Cu':'As'} · {t==='cu'?'g/L':'mg/L'}</span><strong>{pointer.candidate_id==='builtin-persistence'?'Persistence':text(object(artifact?.descriptor).method_id,'尚未读取')}</strong><small>指针版本 {text(pointer.version)}</small></div>;})}</div>
    <Tabs value={tab} onChange={setTab} options={[{id:'registry',label:'方法目录'},{id:'comparisons',label:'模型比较'},{id:'artifacts',label:'工件与发布'},{id:'calibration',label:'区间校准'},{id:'ensembles',label:'集成研究'},{id:'legacy',label:'已有预测模型'}]}/>
    {error?<Notice tone="error">{error}</Notice>:null}
    {tab==='legacy'?legacy:tab==='registry'?<><Toolbar title="注册方法" onRefresh={catalog.reload}><input aria-label="搜索方法" placeholder="搜索模型或实现…" value={search} onChange={e=>setSearch(e.target.value)}/></Toolbar><Notice>登记状态说明接口可用性。训练、测试、比较与发布证据请查看对应工件。</Notice>{catalog.error?<Notice tone="error">{catalog.error}</Notice>:null}{catalog.loading&&!catalog.data?<Loading/>:<DataTable rows={methods} onRow={row=>setSelection({kind:'method',row})} columns={[{key:'method_id',label:'方法'},{key:'multi_output',label:'输出形式',render:r=>outputLabel(r.multi_output)},{key:'method_version',label:'方法版本'},{key:'uncertainty',label:'区间能力',render:r=>uncertaintyLabel(r.uncertainty??object(r.capabilities).uncertainty)},{key:'status',label:'登记状态',render:r=><Status value={r.status}/>}]}/>}</>:<>
      {(tab==='comparisons'||tab==='calibration')?<section className="workspace-panel"><Toolbar title={tab==='calibration'?'创建独立时序校准':'创建模型比较'}/><div className="workspace-choice-grid">{(catalog.data?.items||[]).map(row=>{const id=text(row.method_id);return <label key={id}><input type="checkbox" checked={methodSet.includes(id)} disabled={id==='Persistence'||busy} onChange={e=>setMethodSet(old=>e.target.checked?[...old,id]:old.filter(v=>v!==id))}/>{id}</label>;})}</div><div className="workspace-actions"><label className="field">随机种子<input type="number" min={0} value={seed} onChange={e=>setSeed(Number(e.target.value))}/></label><button className="primary" disabled={busy||!canCompute||!methodSet.length} onClick={()=>void startComparison(tab==='calibration')}><Play size={16}/>{busy?'正在登记…':'开始研究'}</button></div>{tab==='calibration'?<p className="workspace-note">基础拟合、校准与外层验证按时间分开。90% 是名义水平，结果会显示实际覆盖率。</p>:null}</section>:null}
      {tab==='artifacts'?<section className="workspace-panel"><Toolbar title="登记已有研究工件"/><div className="workspace-form-grid"><label className="field">来源类型<select value={sourceKind} onChange={e=>{setSourceKind(e.target.value);setSourceId('');}}><option value="model_comparison">模型比较</option><option value="calibration_study">校准研究</option><option value="ensemble_study">集成研究</option></select></label><label className="field">已完成来源<select value={sourceId} onChange={e=>setSourceId(e.target.value)}><option value="">选择已完成研究</option>{completed.map(r=><option key={text(r.id??r.run_id)} value={text(r.id??r.run_id)}>{text(object(r.request).request_key??r.id??r.run_id)}</option>)}</select></label><label className="field">方法<input list="source-methods" value={artifactMethod} onChange={e=>setArtifactMethod(e.target.value)}/><datalist id="source-methods">{sourceMethods.map(v=><option key={v} value={v}/>)}</datalist></label><label className="field">目标<select value={target} onChange={e=>setTarget(e.target.value)}><option value="cu">Cu · g/L</option><option value="as">As · mg/L</option></select></label></div><button disabled={busy||!canCompute||!sourceId||!artifactMethod} onClick={()=>void registerArtifact()}><Plus size={15}/>登记工件</button>{operation&&!selection?<Notice tone="success">工件已登记：{text(operation.id)}</Notice>:null}</section>:null}
      <Toolbar title={tab==='artifacts'?'生命周期记录':tab==='ensembles'?'已有集成研究':'研究记录'} onRefresh={()=>{comparisons.reload();calibrations.reload();artifacts.reload();ensembles.reload();}}/>
      {currentCollection.error?<Notice tone="error">{currentCollection.error}</Notice>:null}{currentCollection.loading&&!currentCollection.data?<Loading/>:rows.length?<DataTable rows={rows} onRow={row=>{setGate(null);setShadowId('');setOperation(null);setSelection({kind:tab==='artifacts'?'artifact':tab==='calibration'?'calibration':tab==='ensembles'?'ensemble':'comparison',row});}} columns={[{key:'id',label:tab==='artifacts'?'模型 / 目标':'研究',render:r=><div><strong>{tab==='artifacts'?text(object(r.descriptor).method_id)+' · '+(object(r.descriptor).target==='cu'?'Cu':'As'):text(object(r.request).request_key??r.id??r.run_id)}</strong><small className="workspace-id">{text(r.id??r.run_id)}</small></div>},{key:'status',label:'状态',render:r=><Status value={r.status}/>},{key:'created_at',label:'创建时间',render:r=>date(text(r.created_at))}]}/>:<EmptyState title="尚无对应记录">完成一项研究后，可在这里查看结果和来源。</EmptyState>}
    </>}
    {selection?<Drawer title={selection.kind==='method'?text(selection.row.method_id):selection.kind==='artifact'?'模型工件与发布':'研究结果'} onClose={close}>
      {detail.loading&&!current?<Loading/>:null}{detail.error?<Notice tone="error">{detail.error}</Notice>:null}
      {selection.kind==='method'?<><Facts values={[{label:'实现',value:text(current?.implementation)},{label:'方法版本',value:text(current?.method_version)},{label:'输入字段',value:text(current?.feature_count)},{label:'输出结构',value:text(current?.multi_output)}]}/><JsonDetails value={current}/></>:<>
        <Status value={current?.status}/>{object(current?.error).message?<Notice tone="error">{text(object(current?.error).message)}</Notice>:null}
        {selection.kind==='artifact'?<><Facts values={[{label:'方法',value:text(descriptor.method_id)},{label:'目标 / 单位',value:text(descriptor.target)+' · '+text(descriptor.unit)},{label:'来源',value:text(descriptor.source_kind)},{label:'校准器',value:descriptor.calibrator?'已绑定':'未绑定'}]}/>
          <div className="workspace-actions"><button disabled={busy||!canCompute||!current} onClick={()=>void shadow()}><ShieldCheck size={15}/>运行影子回放</button><button disabled={!shadowId||busy} onClick={()=>void request<RecordValue>('/v2/model-artifacts/'+selectedId+'/qualification?shadow_id='+shadowId).then(setGate).catch(e=>setError(e.message))}>检查发布条件</button></div>
          {gate?<Notice tone={gate.passed?'success':'neutral'}>{gate.passed?'当前满足发布提案条件':'尚未满足：'+((gate.failures as string[])||[]).join('、')}</Notice>:null}
          <button className="primary" disabled={!gate?.passed||busy||!canCompute} onClick={()=>void propose()}>创建发布提案</button>
          {operation?.payload_hash?<section className="workspace-review"><h3>审查具体提案</h3><JsonDetails value={operation} label="查看绑定版本、用途与有效期"/><code>{text(operation.payload_hash)}</code><button disabled={!canApprove||busy} onClick={()=>void execute(()=>request('/v2/releases/'+text(operation.id)+'/approve',{body:{payload_hash:operation.payload_hash,decision:'approve'}}))}>批准此提案</button></section>:null}
          <JsonDetails value={descriptor.benchmark} label="查看完整资格证据"/><JsonDetails value={current}/>
        </>:<>{items(result.metrics).length?<DataTable rows={items(result.metrics)} columns={metricsColumns}/>:<EmptyState title={current?.status==='completed'?'该记录没有汇总指标':'结果尚未生成'}>运行状态和错误以服务器记录为准。</EmptyState>}
          {selection.kind==='calibration'&&current?.status==='completed'&&eventId?<button onClick={()=>void execute(()=>request('/v2/calibrations/'+selectedId+'/predict',{body:{event_id:eventId,method_id:'Persistence'}}))}>回放所选事件的校准区间</button>:null}
          {operation?<JsonDetails value={operation} label="查看操作结果"/>:null}<JsonDetails value={current}/></>}
      </>}
      {error?<Notice tone="error">{error}</Notice>:null}
    </Drawer>:null}
  </section>;
}
