import {useCallback,useEffect,useMemo,useState,type ReactNode} from 'react';
import {Play,Plus} from 'lucide-react';
import {ArtifactActions,ReleaseHistory} from './ModelReleasePanel';
import {DataTable,Drawer,EmptyState,Facts,JsonDetails,Loading,Notice,Status,Tabs,Toolbar,date,fmt,items,object,request,text,useRemote,type RecordValue} from './WorkspaceUI';
const outputLabel=(value:unknown)=>({reference:'当前观测参考',joint:'联合双目标',two_independent_estimators:'双目标独立模型',joint_two_target_head:'联合双目标',two_independent_posterior_models:'双目标后验模型',two_independent_expression_searches:'双目标符号表达式',two_independent_context_models:'双目标预训练模型'} as Record<string,string>)[text(value)]||text(value);
const uncertaintyLabel=(value:unknown)=>{const name=text(value,'');if(!name||name==='unsupported')return '未开放区间';if(name.includes('std'))return '原生标准差（未校准）';if(name.includes('quantile'))return '原生分位数（未校准）';return name;};
const studyLabel=(row:RecordValue)=>Array.isArray(object(row.request).methods)?(object(row.request).methods as string[]).join(' / '):'研究 '+text(row.id??row.run_id).slice(0,12);
const intervalLabels:Record<string,string>={point:'点预测',native:'原生区间',marginal_c90:'边际 C90',joint_c90:'联合 C90'};
type Selection={kind:'method'|'comparison'|'artifact'|'calibration'|'ensemble';row:RecordValue};
const metricsColumns=[{key:'method_id',label:'方法'},{key:'target',label:'目标 / 单位',render:(r:RecordValue)=>(r.target==='cu'?'Cu':'As')+' · '+text(r.unit,r.target==='cu'?'g/L':'mg/L')},{key:'n',label:'样本',render:(r:RecordValue)=>fmt(r.n??r.common_events,0)},{key:'mae',label:'MAE',render:(r:RecordValue)=>fmt(r.mae,4)},{key:'rmse',label:'RMSE',render:(r:RecordValue)=>fmt(r.rmse,4)},{key:'picp',label:'区间覆盖',render:(r:RecordValue)=>r.picp===undefined?'—':fmt(Number(r.picp)*100,1)+'%'}];
export default function ModelsWorkspace({legacy,eventId}:{legacy:ReactNode;eventId:string}){
  const [tab,setTab]=useState('registry'),[search,setSearch]=useState(''),[selection,setSelection]=useState<Selection|null>(null);
  const [methodSet,setMethodSet]=useState<string[]>(['Persistence','DeltaRidge']),[seed,setSeed]=useState(20260911);
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[operation,setOperation]=useState<RecordValue|null>(null);
  const [sourceKind,setSourceKind]=useState('model_comparison'),[sourceId,setSourceId]=useState(''),[artifactMethod,setArtifactMethod]=useState('Persistence'),[target,setTarget]=useState('cu');
  const catalog=useRemote<{items:RecordValue[]}>('/v2/models'),comparisons=useRemote<{items:RecordValue[]}>('/v2/model-comparisons');
  const artifacts=useRemote<{items:RecordValue[]}>('/v2/model-artifacts'),calibrations=useRemote<{items:RecordValue[]}>('/v2/calibrations');
  const ensembles=useRemote<{items:RecordValue[]}>('/v2/ensemble-studies'),pointers=useRemote<RecordValue>('/v2/model-pointers'),info=useRemote<RecordValue>('/v2/workspace');
  const [ensembleSource,setEnsembleSource]=useState(''),[ensembleSeeds,setEnsembleSeeds]=useState('20260911,20260912,20260913,20260914,20260915');
  const [artifactSeed,setArtifactSeed]=useState(''),[calibrationMethod,setCalibrationMethod]=useState('Persistence');
  const refreshAll=useCallback(()=>{artifacts.reload();comparisons.reload();calibrations.reload();ensembles.reload();pointers.reload();},[artifacts.reload,comparisons.reload,calibrations.reload,ensembles.reload,pointers.reload]);
  const close=useCallback(()=>{setSelection(null);setOperation(null);setError('');},[]);
  const canCompute=!!info.data&&object(info.data.user).role!=='viewer',canApprove=object(info.data?.user).role==='owner';
  const paths={comparison:'/v2/model-comparisons/',artifact:'/v2/model-artifacts/',calibration:'/v2/calibrations/',ensemble:'/v2/ensemble-studies/'};
  const selectedId=selection?text(selection.row.id??selection.row.run_id):'';
  const detail=useRemote<RecordValue>(selection&&selection.kind!=='method'?paths[selection.kind]+selectedId:null);
  const current=selection?.kind==='method'?selection.row:detail.data;
  const descriptor=object(current?.descriptor),result=object(current?.result);
  useEffect(()=>{if(!current||!['queued','running'].includes(text(current.status)))return;const timer=setInterval(()=>{detail.reload();refreshAll();},1600);return()=>clearInterval(timer);},[current?.status,detail.reload,refreshAll]);
  const methods=(catalog.data?.items||[]).filter(row=>(text(row.method_id)+' '+text(row.implementation)).toLowerCase().includes(search.toLowerCase()));
  const sources=sourceKind==='calibration_study'?calibrations.data?.items:sourceKind==='ensemble_study'?ensembles.data?.items:comparisons.data?.items;
  const completed=(sources||[]).filter(row=>row.status==='completed');
  const selectedSource=useRemote<RecordValue>(sourceId?(sourceKind==='calibration_study'?'/v2/calibrations/':sourceKind==='ensemble_study'?'/v2/ensemble-studies/':'/v2/model-comparisons/')+sourceId:null);
  const sourceMethods=useMemo(()=>{
    const value=selectedSource.data;if(!value)return [];
    const names=sourceKind==='ensemble_study'?items(object(value.result).metrics).map(row=>text(row.method_id)).filter(id=>!['Persistence','DeltaRidge','DeltaHGB','ElasticNet','Huber','PLS'].includes(id)):(object(value.request).methods as string[]||[]);
    return [...new Set(names)];
  },[selectedSource.data,sourceKind]);
  useEffect(()=>{if(sourceMethods.length&&!sourceMethods.includes(artifactMethod))setArtifactMethod(sourceMethods[0]);setArtifactSeed('');},[sourceMethods,artifactMethod]);
  const availableSeeds=[...new Set(items(object(selectedSource.data?.result).seed_metrics??object(selectedSource.data?.result).metrics).filter(row=>row.method_id===artifactMethod&&row.seed!==null&&row.seed!==undefined).map(row=>Number(row.seed)))];
  const ensembleSources=(comparisons.data?.items||[]).filter(row=>row.status==='completed'&&['Persistence','DeltaRidge','DeltaHGB'].every(method=>(object(row.request).methods as string[]||[]).includes(method)));
  async function execute(action:()=>Promise<RecordValue>){setBusy(true);setError('');try{const value=await action();setOperation(value);refreshAll();detail.reload();return value;}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function startComparison(calibration=false){await execute(async()=>{const payload={request_key:crypto.randomUUID(),methods:methodSet,seeds:[seed]};const value=await request<RecordValue>(calibration?'/v2/calibrations':'/v2/model-comparisons',{body:calibration?payload:{request_key:payload.request_key,methods:methodSet,seed}});setSelection({kind:calibration?'calibration':'comparison',row:value});return value;});}
  async function registerArtifact(){await execute(()=>request('/v2/model-artifacts',{body:{request_key:crypto.randomUUID(),source_kind:sourceKind,source_id:sourceId,method_id:artifactMethod,target,...(artifactSeed!==''?{seed:Number(artifactSeed)}:{})}}));}
  async function startEnsemble(){
    const seeds=ensembleSeeds.split(',').map(v=>Number(v.trim()));
    if(!ensembleSeeds.trim()||!seeds.every(v=>Number.isInteger(v)&&v>=0&&v<2**31)||new Set(seeds).size!==seeds.length||seeds.length>8){setError('请填写 1–8 个不重复的非负整数种子。');return;}
    await execute(async()=>{const value=await request<RecordValue>('/v2/ensemble-studies',{body:{request_key:crypto.randomUUID(),comparison_id:ensembleSource,seeds}});setSelection({kind:'ensemble',row:value});return value;});
  }
  const currentCollection=tab==='comparisons'?comparisons:tab==='calibration'?calibrations:tab==='ensembles'?ensembles:artifacts;
  const rows=tab==='comparisons'?(comparisons.data?.items||[]):tab==='calibration'?(calibrations.data?.items||[]):tab==='ensembles'?(ensembles.data?.items||[]):(artifacts.data?.items||[]);
  return <section className="workspace-stack">
    <div className="workspace-champions">{['cu','as'].map(t=>{const pointer=object(pointers.data?.[t]);const artifact=artifacts.data?.items.find(a=>a.id===pointer.candidate_id);return <div key={t}><span>{t==='cu'?'Cu':'As'} · {t==='cu'?'g/L':'mg/L'}</span><strong>{pointer.candidate_id==='builtin-persistence'?'Persistence':text(object(artifact?.descriptor).method_id,'尚未读取')}</strong><small>指针版本 {text(pointer.version)}</small></div>;})}</div>
    <Tabs value={tab} onChange={setTab} options={[{id:'registry',label:'方法目录'},{id:'comparisons',label:'模型比较'},{id:'artifacts',label:'工件与发布'},{id:'releases',label:'发布历史与回退'},{id:'calibration',label:'区间校准'},{id:'ensembles',label:'集成研究'},{id:'legacy',label:'已有预测模型'}]}/>
    {error?<Notice tone="error">{error}</Notice>:null}
    {pointers.error?<Notice tone="error">{pointers.error}</Notice>:null}
    {tab==='legacy'?legacy:tab==='releases'?<ReleaseHistory canApprove={canApprove} onChanged={refreshAll}/>:tab==='registry'?<><Toolbar title="注册方法" onRefresh={catalog.reload}><input aria-label="搜索方法" placeholder="搜索模型或实现…" value={search} onChange={e=>setSearch(e.target.value)}/></Toolbar><Notice>登记状态说明接口可用性。训练、测试、比较与发布证据请查看对应工件。</Notice>{catalog.error?<Notice tone="error">{catalog.error}</Notice>:null}{catalog.loading&&!catalog.data?<Loading/>:<DataTable rows={methods} onRow={row=>setSelection({kind:'method',row})} columns={[{key:'method_id',label:'方法'},{key:'multi_output',label:'输出形式',render:r=>outputLabel(r.multi_output)},{key:'method_version',label:'方法版本'},{key:'uncertainty',label:'区间能力',render:r=>uncertaintyLabel(r.uncertainty??object(r.capabilities).uncertainty)},{key:'status',label:'登记状态',render:r=><Status value={r.status}/>}]}/>}</>:<>
      {(tab==='comparisons'||tab==='calibration')?<section className="workspace-panel"><Toolbar title={tab==='calibration'?'创建独立时序校准':'创建模型比较'}/><div className="workspace-choice-grid">{(catalog.data?.items||[]).map(row=>{const id=text(row.method_id);return <label key={id}><input type="checkbox" checked={methodSet.includes(id)} disabled={id==='Persistence'||busy} onChange={e=>setMethodSet(old=>e.target.checked?[...old,id]:old.filter(v=>v!==id))}/>{id}</label>;})}</div><div className="workspace-actions"><label className="field">随机种子<input type="number" min={0} value={seed} onChange={e=>setSeed(Number(e.target.value))}/></label><button className="primary" disabled={busy||!canCompute||!methodSet.length} onClick={()=>void startComparison(tab==='calibration')}><Play size={16}/>{busy?'正在登记…':'开始研究'}</button></div>{tab==='calibration'?<p className="workspace-note">基础拟合、校准与外层验证按时间分开。90% 是名义水平，结果会显示实际覆盖率。</p>:null}</section>:null}
      {tab==='artifacts'?<section className="workspace-panel"><Toolbar title="登记已有研究工件"/><div className="workspace-form-grid"><label className="field">来源类型<select value={sourceKind} onChange={e=>{setSourceKind(e.target.value);setSourceId('');}}><option value="model_comparison">模型比较</option><option value="calibration_study">校准研究</option><option value="ensemble_study">集成研究</option></select></label><label className="field">已完成来源<select value={sourceId} onChange={e=>{setSourceId(e.target.value);setArtifactSeed('');}}><option value="">选择已完成研究</option>{completed.map(r=><option key={text(r.id??r.run_id)} value={text(r.id??r.run_id)}>{studyLabel(r)} · {text(r.id??r.run_id).slice(0,8)}</option>)}</select></label><label className="field">方法<select value={artifactMethod} onChange={e=>setArtifactMethod(e.target.value)} disabled={!sourceMethods.length}>{sourceMethods.length?sourceMethods.map(v=><option key={v} value={v}>{v}</option>):<option value="">先选择来源</option>}</select></label><label className="field">目标<select value={target} onChange={e=>setTarget(e.target.value)}><option value="cu">Cu · g/L</option><option value="as">As · mg/L</option></select></label>{availableSeeds.length?<label className="field">拟合种子<select value={artifactSeed} onChange={e=>setArtifactSeed(e.target.value)}><option value="">来源默认种子</option>{availableSeeds.map(value=><option key={value} value={value}>{value}</option>)}</select></label>:null}</div><button disabled={busy||!canCompute||!sourceId||!sourceMethods.includes(artifactMethod)} onClick={()=>void registerArtifact()}><Plus size={15}/>登记工件</button>{operation&&!selection?<Notice tone="success">工件已登记：{text(operation.id)}</Notice>:null}</section>:null}
      {tab==='ensembles'?<section className="workspace-panel"><Toolbar title="创建集成研究"/><label className="field">基模型比较<select value={ensembleSource} onChange={e=>setEnsembleSource(e.target.value)}><option value="">选择已完成比较</option>{ensembleSources.map(row=><option key={text(row.run_id)} value={text(row.run_id)}>{studyLabel(row)} · {text(row.run_id).slice(0,8)}</option>)}</select></label>
        {!ensembleSources.length?<Notice>需要先完成包含 Persistence、DeltaRidge、DeltaHGB 的比较。<button onClick={()=>{setMethodSet(['Persistence','DeltaRidge','DeltaHGB']);setTab('comparisons');}}>配置所需基模型比较</button></Notice>:null}
        <label className="field">集成随机种子（逗号分隔）<input value={ensembleSeeds} onChange={e=>setEnsembleSeeds(e.target.value)}/></label>
        <button className="primary" disabled={busy||!canCompute||!ensembleSource} onClick={()=>void startEnsemble()}><Play size={15}/>开始集成研究</button><p className="workspace-note">按来源协议执行嵌套时序拟合、融合和同基模型对照，结果在完成后显示。</p></section>:null}
      <Toolbar title={tab==='artifacts'?'生命周期记录':tab==='ensembles'?'已有集成研究':'研究记录'} onRefresh={()=>{comparisons.reload();calibrations.reload();artifacts.reload();ensembles.reload();}}/>
      {currentCollection.error?<Notice tone="error">{currentCollection.error}</Notice>:null}{currentCollection.loading&&!currentCollection.data?<Loading/>:rows.length?<DataTable rows={rows} onRow={row=>{setOperation(null);setSelection({kind:tab==='artifacts'?'artifact':tab==='calibration'?'calibration':tab==='ensembles'?'ensemble':'comparison',row});}} columns={[{key:'id',label:tab==='artifacts'?'模型 / 目标':'研究',render:r=><div><strong>{tab==='artifacts'?text(object(r.descriptor).method_id)+' · '+(object(r.descriptor).target==='cu'?'Cu':'As'):studyLabel(r)}</strong><small className="workspace-id">{text(r.id??r.run_id)}</small></div>},{key:'status',label:'状态',render:r=><Status value={r.status}/>},{key:'created_at',label:'创建时间',render:r=>date(r.created_at)}]}/>:<EmptyState title="尚无对应记录">完成一项研究后，可在这里查看结果和来源。</EmptyState>}
    </>}
    {selection?<Drawer title={selection.kind==='method'?text(selection.row.method_id):selection.kind==='artifact'?'模型工件与发布':'研究结果'} onClose={close}>
      {detail.loading&&!current?<Loading/>:null}{detail.error?<Notice tone="error">{detail.error}</Notice>:null}
      {selection.kind==='method'?<><Facts values={[{label:'实现',value:text(current?.implementation)},{label:'方法版本',value:text(current?.method_version)},{label:'输入字段',value:text(current?.feature_count)},{label:'输出结构',value:text(current?.multi_output)}]}/><JsonDetails value={current}/></>:<>
        <Status value={current?.status}/>{object(current?.error).message?<Notice tone="error">{text(object(current?.error).message)}</Notice>:null}
        {selection.kind==='artifact'?<><Facts values={[{label:'方法',value:text(descriptor.method_id)},{label:'目标 / 单位',value:(descriptor.target==='cu'?'Cu':'As')+' · '+text(descriptor.unit)},{label:'来源',value:text(descriptor.source_kind)},{label:'校准器',value:descriptor.calibrator?'已绑定':'未绑定'}]}/>
          {current?<ArtifactActions key={selectedId} artifact={current} canCompute={canCompute} canApprove={canApprove} isCurrent={Object.values(pointers.data||{}).some(value=>object(value).candidate_id===selectedId)} onChanged={refreshAll}/>:null}
          <JsonDetails value={descriptor.benchmark} label="查看完整资格证据"/><JsonDetails value={current}/>
        </>:<>{items(result.metrics).length?<DataTable rows={items(result.metrics)} columns={selection.kind==='calibration'?[{key:'mode',label:'区间类型',render:r=>intervalLabels[text(r.mode)]||text(r.mode)},{key:'seed',label:'拟合种子'},...metricsColumns,{key:'normalized_width',label:'标准化宽度',render:r=>fmt(r.normalized_width,3)}]:metricsColumns}/>:<EmptyState title={current?.status==='completed'?'该记录没有汇总指标':'结果尚未生成'}>运行状态和错误以服务器记录为准。</EmptyState>}
          {selection.kind==='calibration'&&current?.status==='completed'&&eventId?<><label className="field">区间回放方法<select value={calibrationMethod} onChange={e=>setCalibrationMethod(e.target.value)}>{[...new Set(items(result.metrics).map(row=>text(row.method_id)))].map(method=><option key={method} value={method}>{method}</option>)}</select></label><button disabled={busy||!canCompute} onClick={()=>void execute(()=>request('/v2/calibrations/'+selectedId+'/predict',{body:{event_id:eventId,method_id:calibrationMethod}}))}>回放所选事件的校准区间</button></>:null}
          {selection.kind==='ensemble'&&['failed','interrupted'].includes(text(current?.status))?<button disabled={busy||!canCompute} onClick={()=>void execute(()=>request('/v2/ensemble-studies/'+selectedId+'/resume',{body:{}}))}>恢复已保存的集成研究</button>:null}
          {operation?<JsonDetails value={operation} label="查看操作结果"/>:null}<JsonDetails value={current}/></>}
      </>}
      {error?<Notice tone="error">{error}</Notice>:null}
    </Drawer>:null}
  </section>;
}
